//
// Created by sam on 18/02/2022.
//

#ifndef TENSOR_PLAYGROUND_SRC_BENCH_PARAMS_H_
#define TENSOR_PLAYGROUND_SRC_BENCH_PARAMS_H_

#ifndef PLAYGROUND_BENCH_WIDTH
#define WIDTH 5
#else
#define WIDTH PLAYGROUND_BENCH_WIDTH
#endif
#ifndef PLAYGROUND_BENCH_DEPTH
#define DEPTH 12
#else
#define DEPTH PLAYGROUND_BENCH_DEPTH
#endif

#endif//TENSOR_PLAYGROUND_SRC_BENCH_PARAMS_H_
